# Foreground / background
foreground            #D8DEE9
background            #2E3440
selection_foreground  #ECEFF4
selection_background  #5E81AC

# URL color
url_color             #88C0FF

# black
color0  #2E3440
color8  #4C566A

# red
color1  #BF616A
color9  #D08770

# green
color2  #A3BE8C
color10 #B5D19A

# yellow
color3  #EBCB8B
color11 #EFD49F

# blue
color4  #88C0FF
color12 #AACCFF

# magenta
color5  #B48EAD
color13 #C895BF

# cyan
color6  #88C0D0
color14 #8FBCBB

# white
color7  #D8DEE9
color15 #ECEFF4

# Cursor colors
cursor            #D8DEE9
cursor_text_color #2E3440

# Tab bar colors
active_tab_foreground   #ECEFF4
active_tab_background   #5E81AC
inactive_tab_foreground #D8DEE9
inactive_tab_background #4C566A

# Marks
mark1_foreground #2E3440
mark1_background #88C0FF

# Splits / windows
active_border_color   #5E81AC
inactive_border_color #4C566A

# Transparency
background_opacity 0.85
